project addition: Added Discord Bot Project
priyankarpal/ProjectsHut pull request #1218
Opened 2023-06-15 11:37 UTC by killerraj369

## Related Issue
Issue No - #1201

## Description
A Discord Bot for Coders. Now Contests and Hackathons related Information under your command. Executes Code in Discord Itself. Provides Jokes, News, Quotes and fun things. Supported - C, C++, Python, Java, JavaScript, Golang, C# etc.

## Screenshots

![2023-06-15 (4)](https://github.com/priyankarpal/ProjectsHut/assets/87773889/4ca200ff-437c-4097-9ac7-a74c798c92a7)
![2023-06-15 (2)](https://github.com/priyankarpal/ProjectsHut/assets/87773889/94b0d2c6-0e51-4983-91d8-31ecf3aeeef1)
![2023-06-15 (3)](https://github.com/priyankarpal/ProjectsHut/assets/87773889/53fcbc3e-d1bc-49c2-9505-7f933a35e766)

2023-06-15 11:41 UTC, killerraj369 commented
Kindly Review the PR, and tell if changes are required else you can merge the PR

2023-06-15 13:40 UTC, priyankarpal requested changes

2023-06-15 13:40 UTC, priyankarpal commented on src/DB/projects.json
> +        "Twitter": ""
remove these code if you're not using

2023-06-15 13:40 UTC, priyankarpal commented on src/DB/projects.json
> +        },
remove the comma `,`
```suggestion
        }
```

2023-06-18 06:47 UTC, killerraj369 commented
Hey @priyankarpal  I have made all the required changes and resolved conflicts.  All Checks have also passed.
Kindly Take a review and merge my PR.

2023-06-18 06:50 UTC, killerraj369 reviewed
I have made all the changes required

2023-06-18 15:17 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-06-18 15:17 UTC, merged