Update projects.json
priyankarpal/ProjectsHut pull request #1368
Opened 2023-06-24 20:31 UTC by MisterMickey

## Related Issue

closes #1346 

## Description

Navbar project using React addition

![Screenshot from 2023-06-25 01-59-47](https://github.com/priyankarpal/ProjectsHut/assets/93720428/2c2ad747-4943-48fe-b7df-f18af669dd74)

## Checklist for projects addition 
 
- [x] My project has a README file.

2023-06-24 20:37 UTC, priyankarpal requested changes
ig it's not a valid project also,in order to merge the pull request, it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.

2023-06-24 20:40 UTC, MisterMickey commented
@priyankarpal Sure, I'll do that.

2023-06-24 20:50 UTC, MisterMickey commented
I have added CONTRIBUTING.md, Code of Conduct and License. @priyankarpal 

![Screenshot from 2023-06-25 02-19-08](https://github.com/priyankarpal/ProjectsHut/assets/93720428/28dc69c7-e4c8-4211-8663-ad15c583e8ba)

2023-06-25 04:52 UTC, priyankarpal approved these changes

2023-06-25 04:52 UTC, merged