Educational Website
priyankarpal/ProjectsHut pull request #1474
Opened 2023-06-30 16:34 UTC by Ks103

## Related Issue
#1442 

## Description

This is the educational website, one can practice their skills and there are many resources also available which can help to crack GATE.
  

## Screenshots

![Screenshot (209)](https://github.com/priyankarpal/ProjectsHut/assets/86292101/aa75a119-0cf2-474c-bba9-98643b8057c6)

## Checklist for projects addition

 

- [ ] My project has contribution guidelines.
- [ ] My project has a Code of Conduct.
- [ ] My project has a README file.
- [ ] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

2023-06-30 19:22 UTC, priyankarpal approved these changes

2023-06-30 19:23 UTC, priyankarpal requested changes

2023-06-30 19:23 UTC, priyankarpal commented on src/DB/projects.json
> +      "link": "https://github-usernamefind.netlify.app/",
add github repo link

2023-06-30 19:23 UTC, priyankarpal commented on src/DB/projects.json
> +      "link": "https://khushitech.netlify.app/",
add github repo link

2023-06-30 19:23 UTC, priyankarpal commented on src/DB/projects.json
> +      "link": "https://communicore.netlify.app/",
add github repo link

2023-06-30 19:43 UTC, Ks103 commented
What changes are there @priyankarpal ? I have fixed please check

2023-06-30 20:15 UTC, priyankarpal commented
> What changes are there @priyankarpal ? I have fixed please check

you have added production links but you need to add github repo link. After I can merge

2023-07-01 04:35 UTC, Ks103 commented
done with the changes @priyankarpal

2023-07-01 06:04 UTC, priyankarpal requested changes

2023-07-01 06:04 UTC, priyankarpal commented on src/DB/projects.json
> +      "tech": "[Html,Css,Js]"
change these tags 
```suggestion
      "tech": ["Html","Css","Js"]
```

2023-07-01 06:04 UTC, priyankarpal commented on src/DB/projects.json
> +      "tech": "[Html,Css,Js]"
change these tags
```suggestion
      "tech": ["Html","Css","Js"]
```

2023-07-02 04:18 UTC, Ks103 commented
Done with the changes @priyankarpal

2023-07-02 07:39 UTC, priyankarpal approved these changes

2023-07-02 07:40 UTC, merged