feat: added a project
priyankarpal/ProjectsHut pull request #1577
Opened 2023-07-04 17:20 UTC by Illaf

## Related Issue

Closes #1480 

## Description

Added the UI design of a cat purchasing website

## Screenshots

2023-07-05 13:09 UTC, priyankarpal requested changes

2023-07-05 13:09 UTC, priyankarpal commented on DB/projects.json
> +      "link": "https://illaf.github.io/The-Cat-Store/",
add github link

2023-07-05 18:34 UTC, Illaf commented
@priyankarpal I have added the changes. Please merge now

2023-07-06 03:45 UTC, priyankarpal approved these changes

2023-07-06 03:45 UTC, merged

2023-07-07 06:06 UTC, Illaf commented
@priyankarpal Please add a GSSOC tag in this PR . I am  a GSSOC contributor. It is necessaary for me!

2023-07-07 13:39 UTC, priyankarpal commented
> @priyankarpal Please add a GSSOC tag in this PR . I am a GSSOC contributor. It is necessaary for me!

previously we've added but currently, We are not providing any labels for project additions as they are not associated with solving any issues.