Feat: Added Options Button in Docs page.
priyankarpal/ProjectsHut pull request #1593
Opened 2023-07-05 17:51 UTC by adity2911

## Related Issue
#1519

## Description
I have added the button that partitions the two methods of showing how to contribute to the user.

## Screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/72987111/05d80ea6-9800-4904-bac7-b6c21d7eb48f)

2023-07-06 03:43 UTC, priyankarpal commented
will check soon

2023-07-06 14:17 UTC, priyankarpal requested changes

2023-07-06 14:17 UTC, priyankarpal commented on app/docs/page.tsx
line no. `164` just add only `cursor-pointer text-indigo-600` & remove other tailwind CSS classes

2023-07-06 14:17 UTC, priyankarpal commented on app/docs/page.tsx
line no `174` 

update the code to 
```
<SyntaxHighlighter language="nginx" style={anOldHope}>
```

2023-07-06 14:17 UTC, priyankarpal commented on app/docs/page.tsx
line no `179` modify to 
```
 <Image src={image} alt={text} className="mt-2" width={10000} height={600} />
```

2023-07-06 14:17 UTC, priyankarpal commented on app/docs/page.tsx
> +            className={`mx-2 px-4 py-2 rounded-lg mb-4 ${selectedOption === 0 ? "bg-indigo-600 text-white animate-pulse" : "bg-gray-800 text-gray-300"
modify the code to 

``` suggestion
            className={`mx-2 px-4 py-2 rounded-lg mb-4 ${selectedOption === 0 ? "bg-indigo-600 text-white" : "border border-gray-700 text-gray-300"
```

2023-07-06 14:17 UTC, priyankarpal commented on app/docs/page.tsx
> +            className={`mx-2 px-4 py-2 rounded-lg mb-4 ${selectedOption === 1 ? "bg-indigo-600 text-white animate-pulse" : "bg-gray-800 text-gray-300"
```suggestion
            className={`mx-2 px-4 py-2 rounded-lg mb-4 ${selectedOption === 1 ? "bg-indigo-600 text-white" : "border border-gray-700 text-gray-300"
```

2023-07-06 15:17 UTC, adity2911 commented
@priyankarpal The reviewed changes have been resolved.

2023-07-06 15:55 UTC, priyankarpal requested changes

2023-07-06 15:55 UTC, priyankarpal commented on app/docs/page.tsx
line no `144` 
```
Cannot set properties of null (setting 'innerText')
```

2023-07-06 16:00 UTC, adity2911 commented
Okay let me look into it.

2023-07-06 21:22 UTC, adity2911 commented
Resolved.

2023-07-07 13:41 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-07-07 13:41 UTC, merged