chore: project addition by SurajG20
priyankarpal/ProjectsHut pull request #1641
Opened 2023-07-08 18:20 UTC by SurajG20

Added Projects

## Related Issue
#1641 issue number

## Description

Added Project as previous one had some conflicts

## Screenshots

2023-07-08 19:20 UTC, priyankarpal requested changes
add issue number. you've added PR number

2023-07-09 04:45 UTC, SurajG20 commented
> add issue number. you've added PR number

What's the difference, this is first addition of project ? i removed my previous pull request.

2023-07-09 04:47 UTC, priyankarpal commented
> > add issue number. you've added PR number
> 
> What's the difference, this is first addition of project ? i removed my previous pull request.

before creating the PR you need to create an issue first

2023-07-09 05:08 UTC, priyankarpal requested changes

2023-07-09 05:08 UTC, priyankarpal commented on DB/projects.json
> +      "link": "https://www.surajgoswami.me/",
add github repo link

2023-07-09 05:08 UTC, priyankarpal commented on DB/projects.json
> +      "link": "https://cinemato-two.vercel.app/",
add github repo link

2023-07-09 05:08 UTC, priyankarpal commented on DB/projects.json
> +      "link": "https://surajg20.github.io/Weather-App/",
add github repo link

2023-07-09 05:16 UTC, SurajG20 commented on DB/projects.json
> +      "link": "https://www.surajgoswami.me/",
just added can you check?

2023-07-09 05:17 UTC, priyankarpal approved these changes
Thank you for contributing your projects here 👏🏻 🎉

2023-07-09 05:17 UTC, merged