Adding Account details and projects for first time on ProjectHub
priyankarpal/ProjectsHut pull request #1694
Opened 2023-07-14 03:48 UTC by Panth1823

## Description

## Screenshots

![Screenshot](https://github.com/priyankarpal/ProjectsHut/assets/89696311/6fd3e73e-aa72-4feb-be5e-48c5693189b9)

2023-07-14 13:53 UTC, priyankarpal requested changes
@Panth1823 add the issue number.

2023-07-14 16:06 UTC, Panth1823 commented
How to add an issue number? @priyankarpal

2023-07-14 17:58 UTC, priyankarpal commented
> How to add an issue number? @priyankarpal

have you created an issue for this PR? @Panth1823

2023-07-15 03:10 UTC, Panth1823 commented
chore: project addition by [Panth1823] #1710

2023-07-15 06:16 UTC, priyankarpal requested changes
change the PR title to ` chore: project addition by Panth1823 #1710 `

2023-07-15 06:19 UTC, priyankarpal requested changes

2023-07-15 06:19 UTC, priyankarpal commented on DB/projects.json
>  ]
remove
```suggestion

```

2023-07-15 06:19 UTC, priyankarpal commented on DB/projects.json
>  }
add a `,`
```suggestion
},
```

2023-07-15 06:19 UTC, priyankarpal commented on DB/projects.json
> +}
add `]`
```suggestion
}]
```

2023-07-15 06:19 UTC, priyankarpal commented on DB/projects.json
> +      "tech": ["reactjs", "tailwind"]
rename to `tailwindcss`
```suggestion
      "tech": ["reactjs", "tailwindcss"]
```

2023-07-15 06:20 UTC, priyankarpal commented
> chore: project addition by [Panth1823] #1710

you have to add the issue number to the PR description. It's a best practice.

2023-07-15 07:56 UTC, closed without merging