added firebase and express to filters
priyankarpal/ProjectsHut pull request #1739
Opened 2023-07-16 19:20 UTC by Sahilll15

## Related Issue
Closes #1735 
Title: Addition of Express and Firebase to Filters

Description
This pull request adds Express and Firebase to the existing list of technologies in the utils/techStack.ts file. The techStack array now includes the following technologies:

const techStack = [
  "reactjs",
  "nodejs",
  "nextjs",
  "javaScript",
  "python",
  "mongodb",
  "typescript",
  "express",
  "firebase"
];

Please review and merge this pull request to incorporate these changes into the project.

Screenshots:-
earlier:-
![Screenshot 2023-07-16 at 10 36 58 PM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/cf44f772-d23c-4fe8-9434-51ea40df6481)

updated:-
<img width="447" alt="Screenshot 2023-07-17 at 12 49 47 AM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/10d232d0-c04e-4d52-9a97-1c3297c395e0">

2023-07-16 19:34 UTC, Sahilll15 commented
@priyankarpal have a look!!

2023-07-17 03:04 UTC, priyankarpal requested changes

2023-07-17 03:04 UTC, priyankarpal commented on utils/techStack.ts
> +  "express",
rename to `expressjs`
```suggestion
  "expressjs",
```

2023-07-17 03:58 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-07-17 04:00 UTC, merged