chore: project addition by ratishjain12 #1782
priyankarpal/ProjectsHut pull request #1783
Opened 2023-07-21 05:52 UTC by ratishjain12

I have added my projects and profile please review and merge it

2023-07-21 18:17 UTC, priyankarpal requested changes
@ratishjain12 also, add the issue number to the PR description

2023-07-21 18:17 UTC, priyankarpal commented on DB/projects.json
> +        "link": "https://discord-clone-sepia.vercel.app/",
add the github repo link

2023-07-21 18:17 UTC, priyankarpal commented on DB/projects.json
> +        "link": "https://blogify-mern-app.vercel.app/",
add the github repo link

2023-07-21 18:17 UTC, priyankarpal commented on DB/projects.json
> +        "tech": ["html", "tailwindcss", "javascript", "GSAP"]
change to lowercase 
```suggestion
        "tech": ["html", "tailwindcss", "javascript", "gsap"]
```

2023-07-22 05:30 UTC, ratishjain12 commented on DB/projects.json
> +        "link": "https://discord-clone-sepia.vercel.app/",
I have resolved this

2023-07-22 05:30 UTC, ratishjain12 commented on DB/projects.json
> +        "link": "https://blogify-mern-app.vercel.app/",
I have resolved this

2023-07-22 05:30 UTC, ratishjain12 commented on DB/projects.json
> +        "tech": ["html", "tailwindcss", "javascript", "GSAP"]
I have resolved this

2023-07-22 08:52 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-07-22 08:53 UTC, merged