docs: Added crypto project
priyankarpal/ProjectsHut pull request #1818
Opened 2023-07-23 08:22 UTC by karthiknadar1204

## Related Issue

Clears issue #1789 

## Description
Added a crypto currency project

## Screenshots

2023-07-23 09:28 UTC, priyankarpal requested changes

2023-07-23 09:28 UTC, priyankarpal commented on DB/projects.json
> +        "tech": ["React js", "Chakra UI"]
change the tech stacks

```suggestion
        "tech": ["reactjs", "chakra ui"]
```

2023-07-24 00:15 UTC, karthiknadar1204 commented
will do and push again

2023-07-24 00:51 UTC, karthiknadar1204 commented
Done @priyankarpal

2023-07-24 02:08 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-07-24 02:10 UTC, merged

2023-07-24 11:13 UTC, karthiknadar1204 commented
@priyankarpal Please add the label

2023-07-24 11:14 UTC, priyankarpal commented
> @priyankarpal Please add the label

We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)