feat: implementing dynamic title to pages
priyankarpal/ProjectsHut pull request #1918
Opened 2023-07-31 21:19 UTC by s2sharpit

## Related Issue

Closes: #1875

## Description
Implementing Dynamic Titles for consistency and better SEO

## Screenshots

2023-07-31 21:21 UTC, s2sharpit commented on app/projects/[username]/page.tsx
Hey @priyankarpal, If you thinks the title should be different for this page, let me know.

2023-08-01 13:28 UTC, priyankarpal requested changes

2023-08-01 16:42 UTC, priyankarpal commented on app/projects/[username]/page.tsx
I mean suppose we open a user page then it will show the `user name` to the title

2023-08-01 16:44 UTC, s2sharpit commented on app/projects/[username]/page.tsx
> I mean suppose we open a user page then it will show the `user name` to the title

Okay, Will try my best to implement this. ☺️

2023-08-01 17:26 UTC, s2sharpit commented on app/projects/[username]/page.tsx
Done

2023-08-01 17:50 UTC, priyankarpal requested changes

2023-08-01 17:50 UTC, priyankarpal commented on app/projects/[username]/page.tsx
> +
Define the type for the metadata
```
type Metadata = {
  title: string;
};
```

2023-08-01 17:50 UTC, priyankarpal commented on app/projects/page.tsx
it's a good practice to add types to improve code clarity and maintainability

```
type metadata = {
  title: string;
};
```

2023-08-01 17:50 UTC, priyankarpal commented on app/docs/page.tsx
```
type metadata = {
  title: string;
};
```

2023-08-01 17:50 UTC, priyankarpal commented on app/layout.tsx
We can use these types to ensure type safety when working with the metadata object
```
type Metadata = {
  title: TitleMetadata;
  description: string;
};

type TitleMetadata = {
  default: string;
  template: string;
};

```

2023-08-01 18:08 UTC, priyankarpal commented
> @priyankarpal, I think the better way to add types is to use types provided by NextJs. For example, like this:
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/104740281/257602320-760716e5-5531-42cd-ba79-5f15a156192d.png">
> 
> What so you say?

yeah we can

2023-08-01 18:12 UTC, s2sharpit commented
I have applied the types provided by Nextjs. Kindly review the PR now. ☺️

2023-08-01 18:13 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-08-01 18:14 UTC, merged