chore: project addition by nc1z
priyankarpal/ProjectsHut pull request #1977
Opened 2023-08-06 09:41 UTC by nc1z

### Add a new project to the list
Adding an open source React PWA Starter template, built with Create-React-App, MUI and Firebase

### Record
 - [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
 - [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
 - [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
 - [X] I want to work on this issue

2023-08-06 18:58 UTC, priyankarpal requested changes
@nc1z please add the `issue` number

2023-08-06 18:58 UTC, priyankarpal commented on DB/projects.json
> +        "tech": ["typescript", "react", "firebase", "mui"]
```suggestion
        "tech": ["typescript", "reactjs", "firebase", "mui"]
```

2023-08-06 23:42 UTC, nc1z commented
@priyankarpal do I create a new issue or I'm good to use the PR ticket number? Thanks

2023-08-07 13:05 UTC, priyankarpal commented
> @priyankarpal do I create a new issue or I'm good to use the PR ticket number? Thanks

create a new issue for project addition & add the issue number to the PR description. & add `reactjs` to the tech stacks

2023-08-07 13:11 UTC, priyankarpal requested changes

2023-08-07 13:11 UTC, priyankarpal commented on DB/projects.json
> +      "YouTube": "https://www.youtube.com/@thexitingway",
remove these lines, we stopped collecting `instagram` & `youtube` links

```suggestion

```

2023-08-07 13:11 UTC, priyankarpal commented on DB/projects.json
> +      "gitHub": "https://github.com/Aryainguz",
remove the line 

 ```suggestion
  
```

2023-08-07 14:17 UTC, priyankarpal commented
this branch has a conflicts error. Please resolve it

2023-08-07 14:35 UTC, priyankarpal requested changes

2023-08-07 14:35 UTC, priyankarpal commented on DB/projects.json
> +      "gitHub": "https://github.com/nc1z",
remove the line also 
```suggestion

```

2023-08-07 14:38 UTC, nc1z commented
> > There's quite a bit of formatting errors from previous project additions that have been merged to main. I've just re-added mine instead of editing others. Should be ahead of main now.
> 
> try to create separate branch in future.

Makes sense, apologies relatively new to forking & open source contributing 😄

2023-08-07 14:41 UTC, priyankarpal approved these changes
Thank you for contributing your projects here 👏🏻 🎉

2023-08-07 14:42 UTC, priyankarpal commented
@nc1z  For secure collaboration, remember to check out GitHub's commit signature verification feature. It helps ensure the authenticity of commits and prevents tampering.

Learn how it works: [GitHub Docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)

Happy coding! 😄

2023-08-07 14:42 UTC, merged