chore: Added new project
priyankarpal/ProjectsHut pull request #1985
Opened 2023-08-06 16:02 UTC by soubhik-111

## Related Issue
Added a new project name Kaun Banega Crorepati

## Description
Kaun Banega Crorepati (KBC) Frontend Project is an interactive web application inspired by the popular Indian television quiz show, "Kaun Banega Crorepati," where contestants answer multiple-choice questions to win cash prizes. This frontend project is built using HTML, CSS, and JavaScript to create a user-friendly and engaging experience for users.

## Screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/90599826/426bfa1d-1c77-4549-a166-084bed407cad)

2023-08-06 16:04 UTC, soubhik-111 commented
Issue Number #1978

2023-08-06 18:55 UTC, priyankarpal requested changes

2023-08-06 18:55 UTC, priyankarpal commented on DB/projects.json
> +      "tech": ["HTML", "CSS", "JAVASCRIPT"]
convert all tech stacks to lowercase 
```suggestion
      "tech": ["html", "css", "javascript"]
```

2023-08-07 13:09 UTC, priyankarpal requested changes

2023-08-07 14:24 UTC, soubhik-111 commented on DB/projects.json
> +    "Twitter": ""
May I know why we need to delete Instagram Youtube and twitter all three?

2023-08-07 14:28 UTC, priyankarpal commented on DB/projects.json
> +    "Twitter": ""
currently we are collecting only Twitter, LinkedIn & GitHub accounts link. You haven't added Twitter link so I requested you to remove the Twitter link. For GitHub we are uisgn your GitHub username to show the GitHub icon @soubhik-111

2023-08-07 17:08 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-08-07 17:09 UTC, merged