app landing page is added
priyankarpal/ProjectsHut pull request #2020
Opened 2023-08-08 16:36 UTC by Sushilverma002

## Related Issue

close issue-> #2013 
## Description

app landing page PROJECT is added
## Screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/114687502/e18ede49-54c4-47e3-b3e9-99e65721cd52)

2023-08-08 16:39 UTC, Sushilverma002 commented
@priyankarpal have a look!!

2023-08-08 19:41 UTC, priyankarpal requested changes

2023-08-08 19:41 UTC, priyankarpal commented on DB/projects.json
> +        "tech": ["html", "css", "bootstrap","js"]
change to `javascript`

```suggestion
        "tech": ["html", "css", "bootstrap","javascript"]
```

2023-08-09 01:12 UTC, Sushilverma002 commented
@priyankarpal changes a done have a look.

2023-08-09 05:09 UTC, priyankarpal approved these changes

2023-08-09 05:09 UTC, merged

2023-08-09 05:34 UTC, Sushilverma002 commented
Please add level label and GGSoC'23

2023-08-09 05:34 UTC, Sushilverma002 commented
@priyankarpal

2023-08-09 07:40 UTC, Sushilverma002 commented
@priyankarpal please add level label and GGSoC'23 label so that I get points for this Pr

2023-08-09 07:45 UTC, priyankarpal commented
> @priyankarpal please add level label and GGSoC'23 label so that I get points for this Pr

We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)