Update contributing.md
priyankarpal/ProjectsHut pull request #2101
Opened 2023-08-29 09:29 UTC by Sahilll15

## Related Issue

closes #2094

## Description

Created a short video providing an overview on how to make your first PR and added it to contributing.md

## Screenshots
![Screenshot 2023-08-29 at 2 56 36 PM](https://github.com/Sahilll15/ProjectsHut/assets/109215419/18b9b117-10a2-4289-9198-99c36ed79f8e)

2023-08-29 18:37 UTC, priyankarpal requested changes

2023-08-29 18:47 UTC, Sahilll15 commented
Other then that is the video fine?? @priyankarpal i

2023-08-30 06:14 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-08-30 06:15 UTC, priyankarpal commented
> Other then that is the video fine?? @priyankarpal

I think it's ok, newbies can understand

2023-08-30 06:15 UTC, merged