Update projects.json
priyankarpal/ProjectsHut pull request #2177
Opened 2023-10-06 09:34 UTC by mohitd404

## Related Issue

<!-- Added A clean, beautiful, responsive portfolio template for Software Developers!

## Description

<!-- A clean, beautiful, responsive portfolio template for Software Developers!

## Screenshots

![preview](https://github.com/priyankarpal/ProjectsHut/assets/146939900/b469dfaf-4f36-46cd-a5d3-99496b51488c)

2023-10-08 03:36 UTC, priyankarpal requested changes

2023-10-08 03:36 UTC, priyankarpal commented on DB/projects.json
> +      "tech": ["html", "javascript", "CSS"]
convert to smallcase
```suggestion
      "tech": ["html", "javascript", "css"]
```

2023-10-08 04:57 UTC, mohitd404 commented
@priyankarpal made the required changes !

2023-10-09 04:37 UTC, priyankarpal approved these changes

2023-10-09 04:37 UTC, merged