Update projects.json
priyankarpal/projectshut pull request #2446
Opened 2024-03-06 07:30 UTC by Siddharth-Dagar-25

## Related Issue

closes #2445 

## Description

Added a project in DB/projects.json file

## Screenshots

no ss

2024-03-06 07:35 UTC, Siddharth-Dagar-25 commented
@priyankarpal  I raised a PR but it is not passing some of the checks, please look it at once and guide me through the process to pass all the necessary checks.
Thank you.

2024-03-06 14:05 UTC, priyankarpal requested changes

2024-03-06 14:05 UTC, priyankarpal commented on DB/projects.json
> +            "tech": ["React", "JavaScript"]
change to smallcase 
```suggestion
            "tech": ["react", "javascript"]
```

2024-03-06 14:05 UTC, priyankarpal commented on DB/projects.json
> +  },
remove the comma
```suggestion
  }
```

2024-03-07 08:54 UTC, priyankarpal approved these changes

2024-03-07 08:54 UTC, merged