Update README.md
priyankarpal/ProjectsHut pull request #528
Opened 2023-05-21 15:30 UTC by the-amazing-atharva

## Related Issue

fixes #505 
for GSSOC'23
## Suggestion

@priyankarpal I think we should add the Ph. logo here can you provide that in this comment section?

2023-05-21 20:04 UTC, priyankarpal commented on README.md
> ++ Our platform is designed to provide individuals with an exceptional space to showcase their work and engage with a worldwide audience.
remove these lines

2023-05-21 20:05 UTC, priyankarpal requested changes

2023-05-21 20:05 UTC, priyankarpal commented on README.md
> ++ This ensures that our platform can adapt and grow alongside the needs of our users, while maintaining its superior performance and polished aesthetics.
also remove these lines 
```suggestion

```

2023-05-22 17:20 UTC, the-amazing-atharva commented
Done @priyankarpal

2023-05-22 18:09 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-05-22 18:09 UTC, merged