data: project addition by kunal kashyap #682
priyankarpal/ProjectsHut pull request #685
Opened 2023-05-23 15:21 UTC by kunalkashyap-1

## Description

Added new project to the project.json file 

## Screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/91254500/f58cc34b-11ea-480c-bf13-4a2f61d4f043)

2023-05-23 16:38 UTC, priyankarpal commented
could you add issue number to the description?

2023-05-24 04:43 UTC, kunalkashyap-1 commented
Added the issue number 😁

2023-05-24 13:37 UTC, priyankarpal requested changes

2023-05-24 13:37 UTC, priyankarpal commented on src/DB/projects.json
> +      "tech": "[React, Material UI, Express js, cherrio]"
change this 
``` suggestion
      "tech": ["React", "MUI", "Express js", "cherrio"]
```

2023-05-24 14:13 UTC, kunalkashyap-1 commented
Fixed that error from my side, do tell me if it needs any other fix

2023-05-24 14:14 UTC, priyankarpal requested changes

2023-05-24 14:14 UTC, priyankarpal commented on src/DB/projects.json
> +      "tech": ["React", "Material UI", "Express js", "cherrio"],
remove `,` 
```suggestion
      "tech": ["React", "Material UI", "Express js", "cherrio"]
```

2023-05-24 14:18 UTC, kunalkashyap-1 commented
done 😅

2023-05-24 14:18 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-05-24 14:20 UTC, merged