added new project
priyankarpal/ProjectsHut pull request #803
Opened 2023-05-25 15:05 UTC by slayerrr12

## Related Issue

https://github.com/priyankarpal/ProjectsHut/issues/801

## Description

addition of new project

## Screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/111631186/01e90e40-c4c1-4041-a501-e3cc323f4ff9)

2023-05-25 15:06 UTC, slayerrr12 commented
@priyankarpal pls review this pr

2023-05-26 04:10 UTC, priyankarpal requested changes

2023-05-26 04:10 UTC, priyankarpal commented on .env.example
add this file

2023-05-26 04:10 UTC, priyankarpal commented on src/DB/projects.json
> +        "tech": ["HTML", "CSS", "Node.js", "VANILLA JAVASCRIPT"]
only Javascript is ok 
``` suggestion
        "tech": ["HTML", "CSS", "Node.js", "Javascript"]
```

2023-05-26 04:24 UTC, slayerrr12 commented on .env.example
ok

2023-05-26 04:25 UTC, closed without merging