feat/docs/fix: changed the colour of the scroll to top button
priyankarpal/ProjectsHut pull request #809
Opened 2023-05-25 16:32 UTC by Bhanuteja01

## Related Issue
#715

## Description
Changed the colour of the scroll to top button

## Screenshots
![Screenshot (6)](https://github.com/priyankarpal/ProjectsHut/assets/110540923/98e1cf34-6d93-4876-9747-8b1c32ca80c5)

![Screenshot (5)](https://github.com/priyankarpal/ProjectsHut/assets/110540923/2e5786c5-82e8-43a9-a634-e6d2ed4f07a6)

2023-05-25 19:35 UTC, ydv-ankit commented
there are some issues. should correct them

2023-05-26 04:27 UTC, priyankarpal requested changes

2023-05-26 04:27 UTC, priyankarpal commented on package-lock.json
remove this file. Please check docs we are suing `pnpm` so use `pnpm` instead of `npm`

2023-05-26 04:29 UTC, priyankarpal commented
also bg not showing

2023-05-26 04:45 UTC, Bhanuteja01 commented
> also bg not showing

what is reason it not showing now

2023-05-26 04:56 UTC, closed without merging