sitemap addtion
priyankarpal/ProjectsHut pull request #914
Opened 2023-05-27 14:58 UTC by krishnamangal98

#854 

## addition of sitemap

## Screenshots
![Screenshot (64)](https://github.com/priyankarpal/ProjectsHut/assets/117482655/8053eb3b-2f1a-4b73-84a9-f5ce2b5f5584)

2023-05-27 18:59 UTC, priyankarpal requested changes

2023-05-27 18:59 UTC, priyankarpal commented on public/sitemap.xml
> +</urlset>
hey @krishnamangal98 we have a few pages such as the `projects` page, and `docs` page so ig we need to add sitemap for those pages as well

2023-05-28 08:59 UTC, krishnamangal98 commented
I have updated the code.
please check it now

2023-05-28 10:42 UTC, priyankarpal requested changes
there are some formatting issues. Please correct with this new one

```<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
                            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

  <url>
    <loc>https://projectshut.vercel.app/</loc>
    <lastmod>2023-05-26T14:19:26+00:00</lastmod>
  </url>

  <url>
    <loc>https://projectshut.vercel.app/projects</loc>
    <lastmod>2023-05-26T14:19:26+00:00</lastmod>
  </url>

  <url>
    <loc>https://projectshut.vercel.app/docs</loc>
    <lastmod>2023-05-26T14:19:26+00:00</lastmod>
  </url>

  <url>
    <loc>https://github.com/priyankarpal/ProjectsHut</loc>
    <lastmod>2023-05-26T14:19:26+00:00</lastmod>
  </url>

</urlset>
```

2023-05-28 16:50 UTC, krishnamangal98 commented
updated.

2023-05-28 16:54 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-05-28 16:56 UTC, merged