feat: sticky navbar done
priyankarpal/ProjectsHut pull request #942
Opened 2023-05-28 08:21 UTC by SINJINI-G

## Related Issue

fixes #897 

## Description

- the navbar is made sticky for better user navigation
- navbar alignment updated

## Screenshots
![poc](https://github.com/priyankarpal/ProjectsHut/assets/98143022/1e2393eb-58b5-4b3d-89a5-f00cb9940dbc)

2023-05-28 08:28 UTC, priyankarpal requested changes
Please don't change the existing design
![Screenshot from 2023-05-28 13-57-21](https://github.com/priyankarpal/ProjectsHut/assets/88102392/ba9bab31-6aa3-4e1b-b2e4-1a16eb3e8ecc)

- just make it transparent & sticky

2023-05-28 14:14 UTC, SINJINI-G commented
> Please don't change the existing design ![Screenshot from 2023-05-28 13-57-21](https://user-images.githubusercontent.com/88102392/241527749-ba9bab31-6aa3-4e1b-b2e4-1a16eb3e8ecc.png)
> 
> * just make it transparent & sticky

Hi @priyankarpal,
- I have made the navbar sticky
- I have reverted to the previous design
- Regarding the transparent thing, the navbar was transparent before I started working on it. Did you mean backdrop opacity by transparent? I was confused so I am attaching herewith the screenshot of the navbar after giving opacity to it.. and also attaching one without it (that is transparent).. let me know which one you need and I will make a PR accordingly.

## Transparent
![poc](https://github.com/priyankarpal/ProjectsHut/assets/98143022/a8a736c2-e72f-4ba6-a173-444aee5d803a)


## Opacity
![poc](https://github.com/priyankarpal/ProjectsHut/assets/98143022/a7a34937-89fd-4ef5-a989-f4f339bfaa7a)

2023-05-28 16:06 UTC, SINJINI-G commented
Hi @priyankarpal !

Can you please tell me which one should I keep and make the PR.. transparent navbar or navbar with opacity?

2023-05-28 16:08 UTC, priyankarpal commented
> Hi @priyankarpal !
> 
> Can you please tell me which one should I keep and make the PR.. transparent navbar or navbar with opacity?

ok so keep the first one it's looking good. if we need to change anything we will change later

2023-05-29 04:33 UTC, SINJINI-G commented
Hi @priyankarpal !! I have made the PR after the latest changes. Kindly review.

2023-05-29 05:15 UTC, priyankarpal commented
but still no changes 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/c0a7143a-24a3-41c1-9e59-b2e6e8cd88d8)

- don't change nav links positions

2023-05-29 06:13 UTC, SINJINI-G commented
Hi @priyankarpal ! Can you check it now?

2023-05-29 08:56 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-05-29 08:58 UTC, merged