Resolved Bug: Sroll Bar starts in the middle
priyankarpal/ProjectsHut pull request #945
Opened 2023-05-28 10:26 UTC by komalioruganti

## Related Issue

 [Bug]: Project Info page opens with scroll bar in the middle  #755

## Description

The bug (Scroll bar starts form the middle of the page when "More" is clicked on Project cards) has been resolved.

## Screenshots

https://github.com/priyankarpal/ProjectsHut/assets/95839946/9b3b6759-9b5c-4c79-89b4-a1d0e7b328df

2023-05-28 10:51 UTC, priyankarpal commented on src/DB/projects.json
> +
you already have added this project so please remove the code

2023-05-29 18:40 UTC, priyankarpal requested changes
could you share your progress on this issue?

2023-05-30 15:14 UTC, closed without merging

2023-05-30 15:17 UTC, komalioruganti commented
I will make a new pull request otherwise

2023-05-30 15:19 UTC, komalioruganti commented
I think I made a mistake. Can you close this pull request... I will make a new pull request. I am contributing for the first time. I am very sorry

2023-05-30 15:34 UTC, komalioruganti commented
I have made a new pull request. Check this one 
Bug resolved: Scroll bar start from middle of page #1012